### ISSUE TITLE
Colorize not working correctly in Windows

### ISSUE THREAD

**Issue by egonelbre** [mfridman/tparse#25]
Currently colorization does not work in Windows Console or PowerShell. Example output:

```
f:\Go\src\sandbox\race>go test -race -json | tparse --all
[1;31m
FAIL: sandbox/race
------------------
[0m--- FAIL: TestRace (0.00s)
    example_test.go:9: 64

+--------+---------+--------------+-------+------+------+------+
| STATUS | ELAPSED |   PACKAGE    | COVER | PASS | FAIL | SKIP |
+--------+---------+--------------+-------+------+------+------+
| [1;31mFAIL[0m   | 0.07s   | sandbox/race | 0.0%  |    0 |    1 |    0 |
+--------+---------+--------------+-------+------+------+------+
```

There is package for coloring compatibility with Windows https://github.com/mattn/go-colorable

**Comment by mfridman** [comment]
@egonelbre I assume when running `go test` without the -race option the colorization still doesn't display?

Thanks for suggestion on mattn/go-colorable. 

Will check `runtime.GOOS` and implement different colorization method for windows and darwin/linux. Hopefully that'll cover majority of use cases.

**Comment by egonelbre** [comment]
Note, using go-colorable shouldn't be too difficult: https://github.com/mattn/go-colorable/blob/master/_example/escape-seq/main.go#L10

Effectively, it's replacing stdout and stderr with the corresponding writer. But disabling is also fine from my standpoint.

**Comment by egonelbre** [comment]
And, yes using `-race` doesn't affect it.

**Comment by mfridman** [comment]
Refactored parts of the code to detect `runtime.GOOS`:
-  `windows` will use colorable pkg 
- `darwin/linux` will use os.Std*

It's currently on a `devel` branch if you want to give it a try. I will try it out on a windows machine tomorrow and merge to master if it works.

**Comment by mfridman** [comment]
@egonelbre Confirmed working on windows. Will merge a fix into master today and push a new release. Thanks for filing an issue.
