### ISSUE TITLE
Path towards v1 - breaking changes (feedback welcome)

### ISSUE THREAD

**Issue by mfridman** [mfridman/tparse#27]
This ticket outlines suggestions for a `v1` build, which may result in _minor_ changes to behaviour.

Feedback received to date:

1. rename flags (name change only):
a. change `-top` to `-reverse`. a flag that changes the ordering of output.
b. change `-dump` to `-replay`. This more accurately reflects what the flag does: replays what `go test` would have printed with the `-json` flag, i.e., standard `go test` output

- this can be done in a backwards compatible way, make sure to alias the existing flags.

2. consider adding table support for benchmarks (currently not supported).

3. some users have tests that run for an extended period of time (minutes). Consider adding a "loading bar" based on bytes read to report that `tparse` is processing items.
- there might be pauses between `go test` output, but that's to be expected
- disabled by default, enabled with a flag. e.g., `-progress`
- if `-dump` (or whatever flag it be replaced with) is added, so long as `-top` (or `-reverse`) is not provided, then just stream the output. We noticed in drone dumping thousands loc slowed down CI.

- partially implemented with #36 (thanks @egonelbre)

4. Consider sorting pass/skip table by package name; looks cleaner to have consistent output.

- this may have been implemented as part of #35 and #36, need to double-check.

**Comment by mfridman** [comment]
Re. item 3 there might be a neat solution to report how many tests have been "seen" or have already "passed"

I've been playing around with https://github.com/mitchellh/go-glint and its dope.

<img width="583" alt="Screen Shot 2020-09-13 at 11 42 47 PM" src="https://user-images.githubusercontent.com/6278244/93041582-dcab0700-f61a-11ea-8b6e-1a3317c73fa1.png">

**Comment by nyonson** [comment]
Would love to see option 4! I work in a rather large repo, and the inconsistent package ordering can be confusing.

**Comment by mfridman** [comment]
Going to carve out some time and address issues/improvements. I still find it useful, especially when refactoring large tests.

**Comment by mfridman** [comment]
Curious @nyonson, are you referring to the summary table, which is currently not ordered but I'm thinking of making it ordered by elapsed DESC or package name ASC

### Tests summary (pass or skip) table

Currently, this one is ordered by elapsed DESC (with option to supply -slow)

```
+--------+---------+-----------------------+---------+
| STATUS | ELAPSED |         TEST          | PACKAGE |
+--------+---------+-----------------------+---------+
| SKIP   |    0.00 | TestCountMallocs      | fmt     |
| PASS   |    0.06 | TestScanInts          | fmt     |
| PASS   |    0.01 | TestIsSpace           | fmt     |
| PASS   |    0.00 | TestErrorf            | fmt     |
| PASS   |    0.00 | TestComplexFormatting | fmt     |
| PASS   |    0.00 | TestReorder           | fmt     |
+--------+---------+-----------------------+---------+
```

### Package summary table

```
+--------+---------+---------+-------+------+------+------+
| STATUS | ELAPSED | PACKAGE | COVER | PASS | FAIL | SKIP |
+--------+---------+---------+-------+------+------+------+
| PASS   | 0.15s   | fmt     | 0.0%  |   75 |    0 |    1 |
| PASS   | 0.85s   | strings | 0.0%  |  115 |    0 |    0 |
| PASS   | 1.12s   | bytes   | 0.0%  |  135 |    0 |    0 |
+--------+---------+---------+-------+------+------+------+
```

**Comment by nyonson** [comment]
Ah, I missed the distinction in the original description. I am referring to the package summary table. I think we would slightly prefer package name ASC, but any ordering would probably result in more consistent output making it easier to eyeball comparisons.

**Comment by mfridman** [comment]
Thanks for the feedback, this is exactly how it'll work. The package tests are grouped by name ASC.

```
┌───────────────────────────────────────────────────────────┐
│  STATUS │ ELAPSED │ PACKAGE │ COVER │ PASS │ FAIL │ SKIP  │
│─────────┼─────────┼─────────┼───────┼──────┼──────┼───────│
│  PASS   │ 0.60s   │ bufio   │ 93.3% │   86 │    0 │    0  │
│  PASS   │ 1.92s   │ bytes   │ 95.6% │  135 │    0 │    0  │
│  PASS   │ 1.04s   │ crypto  │ 5.9%  │    5 │    0 │    0  │
│  PASS   │ 1.23s   │ fmt     │ 95.2% │   75 │    0 │    1  │
│  PASS   │ 0.38s   │ log     │ 68.0% │   10 │    0 │    0  │
│  PASS   │ 0.80s   │ mime    │ 93.8% │   24 │    0 │    0  │
│  PASS   │ 2.25s   │ sort    │ 60.8% │   38 │    0 │    1  │
│  PASS   │ 1.42s   │ strings │ 98.1% │  115 │    0 │    0  │
│  PASS   │ 8.42s   │ time    │ 91.8% │  157 │    0 │    1  │
└───────────────────────────────────────────────────────────┘
```

**Comment by mfridman** [comment]
Going to close this issue in favor of #58.

Lot's of great stuff coming and updates coming.
