### ISSUE TITLE
Show globally slowest tests

### ISSUE THREAD

**Issue by egonelbre** [mfridman/tparse#33]
It would be nice to see N slowest tests globally from all packages.

As an example `go test -a -json fmt testing strings | tparse -nocolor -all -top -slow 4`:

<details>
<pre>
+--------+----------+---------+-------+------+------+------+
| STATUS | ELAPSED  | PACKAGE | COVER | PASS | FAIL | SKIP |
+--------+----------+---------+-------+------+------+------+
| PASS   | (cached) | testing | 0.0%  |   30 |    0 |    0 |
| PASS   | (cached) | fmt     | 0.0%  |   74 |    0 |    1 |
| PASS   | (cached) | strings | 0.0%  |  109 |    0 |    0 |
+--------+----------+---------+-------+------+------+------+

+--------+---------+-----------------------------------------+---------+
| STATUS | ELAPSED |                  TEST                   | PACKAGE |
+--------+---------+-----------------------------------------+---------+
| PASS   |    0.75 | TestBenchmark                           | testing |
| PASS   |    0.52 | TestCompareStrings                      | strings |
| PASS   |    0.26 | TestCaseConsistency                     | strings |
| PASS   |    0.19 | TestRunParallel                         | testing |
+--------+---------+-----------------------------------------+---------+  

+--------+---------+-----------------------------------------+---------+
| STATUS | ELAPSED |                  TEST                   | PACKAGE |
+--------+---------+-----------------------------------------+---------+
| PASS   |    0.75 | TestBenchmark                           | testing |
| PASS   |    0.19 | TestRunParallel                         | testing |
| PASS   |    0.03 | TestBRun                                | testing |
| PASS   |    0.01 | TestTRun                                | testing |
| PASS   |    0.01 | TestIsSpace                             | testing |
| PASS   |    0.00 | TestTBHelper                            | testing |
| PASS   |    0.00 | TestTestContext                         | testing |
| PASS   |    0.00 | TestNaming                              | testing |
| PASS   |    0.00 | TestMatcher                             | testing |
| PASS   |    0.00 | TestBenchmarkOutput                     | testing |
| PASS   |    0.00 | TestBenchmarkStartsFrom1                | testing |
| PASS   |    0.00 | TestBenchmarkReadMemStatsBeforeFirstRun | testing |
| PASS   |    0.00 | TestParallelSub                         | testing |
| PASS   |    0.00 | TestParallelSub/0                       | testing |
| PASS   |    0.00 | TestParallelSub/3                       | testing |
| PASS   |    0.00 | TestParallelSub/5                       | testing |
| PASS   |    0.00 | TestParallelSub/7                       | testing |
| PASS   |    0.00 | TestParallelSub/8                       | testing |
| PASS   |    0.00 | TestParallelSub/4                       | testing |
| PASS   |    0.00 | TestParallelSub/6                       | testing |
| PASS   |    0.00 | TestParallelSub/9                       | testing |
| PASS   |    0.00 | TestParallelSub/2                       | testing |
| PASS   |    0.00 | TestParallelSub/1                       | testing |
| PASS   |    0.00 | TestRacyOutput                          | testing |
| PASS   |    0.00 | TestSplitRegexp                         | testing |
| PASS   |    0.00 | TestAllocsPerRun                        | testing |
| PASS   |    0.00 | TestRoundDown10                         | testing |
| PASS   |    0.00 | TestRoundUp                             | testing |
| PASS   |    0.00 | TestTBHelperParallel                    | testing |
| PASS   |    0.00 | TestRunParallelFail                     | testing |
|        |         |                                         |         |
| SKIP   |    0.00 | TestCountMallocs                        | fmt     |
| PASS   |    0.03 | TestScanInts                            | fmt     |
| PASS   |    0.01 | TestIsSpace                             | fmt     |
| PASS   |    0.00 | TestFmtInterface                        | fmt     |
| PASS   |    0.00 | TestReorder                             | fmt     |
| PASS   |    0.00 | TestFlagParser                          | fmt     |
| PASS   |    0.00 | TestStructPrinter                       | fmt     |
| PASS   |    0.00 | TestSlicePrinter                        | fmt     |
| PASS   |    0.00 | TestMapPrinter                          | fmt     |
| PASS   |    0.00 | TestEmptyMap                            | fmt     |
| PASS   |    0.00 | TestBlank                               | fmt     |
| PASS   |    0.00 | TestBlankln                             | fmt     |
| PASS   |    0.00 | TestFormatterPrintln                    | fmt     |
| PASS   |    0.00 | TestWidthAndPrecision                   | fmt     |
| PASS   |    0.00 | TestPanics                              | fmt     |
| PASS   |    0.00 | TestBadVerbRecursion                    | fmt     |
| PASS   |    0.00 | TestComplexFormatting                   | fmt     |
| PASS   |    0.00 | TestNilDoesNotBecomeTyped               | fmt     |
| PASS   |    0.00 | TestFormatterFlags                      | fmt     |
| PASS   |    0.00 | TestParsenum                            | fmt     |
| PASS   |    0.00 | TestScan                                | fmt     |
| PASS   |    0.00 | TestScan/StringReader                   | fmt     |
| PASS   |    0.00 | TestScan/ReaderOnly                     | fmt     |
| PASS   |    0.00 | TestScan/OneByteReader                  | fmt     |
| PASS   |    0.00 | TestScan/DataErrReader                  | fmt     |
| PASS   |    0.00 | TestScanln                              | fmt     |
| PASS   |    0.00 | TestScanln/StringReader                 | fmt     |
| PASS   |    0.00 | TestScanln/ReaderOnly                   | fmt     |
| PASS   |    0.00 | TestScanln/OneByteReader                | fmt     |
| PASS   |    0.00 | TestScanln/DataErrReader                | fmt     |
| PASS   |    0.00 | TestScanf                               | fmt     |
| PASS   |    0.00 | TestScanOverflow                        | fmt     |
| PASS   |    0.00 | TestNaN                                 | fmt     |
| PASS   |    0.00 | TestInf                                 | fmt     |
| PASS   |    0.00 | TestScanfMulti                          | fmt     |
| PASS   |    0.00 | TestScanfMulti/StringReader             | fmt     |
| PASS   |    0.00 | TestScanfMulti/ReaderOnly               | fmt     |
| PASS   |    0.00 | TestScanfMulti/OneByteReader            | fmt     |
| PASS   |    0.00 | TestScanfMulti/DataErrReader            | fmt     |
| PASS   |    0.00 | TestScanMultiple                        | fmt     |
| PASS   |    0.00 | TestScanEmpty                           | fmt     |
| PASS   |    0.00 | TestScanNotPointer                      | fmt     |
| PASS   |    0.00 | TestScanlnNoNewline                     | fmt     |
| PASS   |    0.00 | TestScanlnWithMiddleNewline             | fmt     |
| PASS   |    0.00 | TestEOF                                 | fmt     |
| PASS   |    0.00 | TestEOFAtEndOfInput                     | fmt     |
| PASS   |    0.00 | TestEOFAllTypes                         | fmt     |
| PASS   |    0.00 | TestUnreadRuneWithBufio                 | fmt     |
| PASS   |    0.00 | TestMultiLine                           | fmt     |
| PASS   |    0.00 | TestLineByLineFscanf                    | fmt     |
| PASS   |    0.00 | TestScanStateCount                      | fmt     |
| PASS   |    0.00 | TestSprintf                             | fmt     |
| PASS   |    0.00 | TestHexBytes                            | fmt     |
| PASS   |    0.00 | TestScanNewlinesAreSpaces               | fmt     |
| PASS   |    0.00 | TestScanlnNewlinesTerminate             | fmt     |
| PASS   |    0.00 | TestScanfNewlineMatchFormat             | fmt     |
| PASS   |    0.00 | TestHexByte                             | fmt     |
| PASS   |    0.00 | TestStringer                            | fmt     |
| PASS   |    0.00 | ExampleErrorf                           | fmt     |
| PASS   |    0.00 | ExampleFscanf                           | fmt     |
| PASS   |    0.00 | ExampleFscanln                          | fmt     |
| PASS   |    0.00 | ExampleSscanf                           | fmt     |
| PASS   |    0.00 | ExamplePrint                            | fmt     |
| PASS   |    0.00 | ExamplePrintln                          | fmt     |
| PASS   |    0.00 | ExamplePrintf                           | fmt     |
| PASS   |    0.00 | ExampleSprint                           | fmt     |
| PASS   |    0.00 | ExampleSprintln                         | fmt     |
| PASS   |    0.00 | ExampleSprintf                          | fmt     |
| PASS   |    0.00 | ExampleFprint                           | fmt     |
| PASS   |    0.00 | ExampleFprintln                         | fmt     |
| PASS   |    0.00 | ExampleFprintf                          | fmt     |
| PASS   |    0.00 | Example_printers                        | fmt     |
| PASS   |    0.00 | Example_formats                         | fmt     |
| PASS   |    0.00 | ExampleGoStringer                       | fmt     |
| PASS   |    0.00 | ExampleStringer                         | fmt     |
|        |         |                                         |         |
| PASS   |    0.52 | TestCompareStrings                      | strings |
| PASS   |    0.26 | TestCaseConsistency                     | strings |
| PASS   |    0.01 | TestBuilderGrow                         | strings |
| PASS   |    0.00 | TestBuilder                             | strings |
| PASS   |    0.00 | TestBuilderWrite2                       | strings |
| PASS   |    0.00 | TestBuilderWrite2/Write                 | strings |
| PASS   |    0.00 | TestBuilderWrite2/WriteRune             | strings |
| PASS   |    0.00 | TestBuilderWrite2/WriteRuneWide         | strings |
| PASS   |    0.00 | TestBuilderWrite2/WriteString           | strings |
| PASS   |    0.00 | TestBuilderWriteByte                    | strings |
| PASS   |    0.00 | TestBuilderAllocs                       | strings |
| PASS   |    0.00 | TestBuilderCopyPanic                    | strings |
| PASS   |    0.00 | TestCompare                             | strings |
| PASS   |    0.00 | TestCompareIdenticalString              | strings |
| PASS   |    0.00 | TestBuilderReset                        | strings |
| PASS   |    0.00 | TestReader                              | strings |
| PASS   |    0.00 | TestReadAfterBigSeek                    | strings |
| PASS   |    0.00 | TestReaderAt                            | strings |
| PASS   |    0.00 | TestReaderAtConcurrent                  | strings |
| PASS   |    0.00 | TestEmptyReaderConcurrent               | strings |
| PASS   |    0.00 | TestWriteTo                             | strings |
| PASS   |    0.00 | TestReaderLenSize                       | strings |
| PASS   |    0.00 | TestReaderReset                         | strings |
| PASS   |    0.00 | TestReaderZero                          | strings |
| PASS   |    0.00 | TestReplacer                            | strings |
| PASS   |    0.00 | TestPickAlgorithm                       | strings |
| PASS   |    0.00 | TestWriteStringError                    | strings |
| PASS   |    0.00 | TestGenericTrieBuilding                 | strings |
| PASS   |    0.00 | TestFinderNext                          | strings |
| PASS   |    0.00 | TestFinderCreation                      | strings |
| PASS   |    0.00 | TestIndex                               | strings |
| PASS   |    0.00 | TestLastIndex                           | strings |
| PASS   |    0.00 | TestIndexAny                            | strings |
| PASS   |    0.00 | TestLastIndexAny                        | strings |
| PASS   |    0.00 | TestLastIndexByte                       | strings |
| PASS   |    0.00 | TestIndexRandom                         | strings |
| PASS   |    0.00 | TestIndexRune                           | strings |
| PASS   |    0.00 | TestSplit                               | strings |
| PASS   |    0.00 | TestSplitAfter                          | strings |
| PASS   |    0.00 | TestFields                              | strings |
| PASS   |    0.00 | TestFieldsFunc                          | strings |
| PASS   |    0.00 | TestMap                                 | strings |
| PASS   |    0.00 | TestToUpper                             | strings |
| PASS   |    0.00 | TestToLower                             | strings |
| PASS   |    0.00 | TestSpecialCase                         | strings |
| PASS   |    0.00 | TestTrimSpace                           | strings |
| PASS   |    0.00 | TestTrim                                | strings |
| PASS   |    0.00 | TestTrimFunc                            | strings |
| PASS   |    0.00 | TestIndexFunc                           | strings |
| PASS   |    0.00 | TestBuilderString                       | strings |
| PASS   |    0.00 | TestRepeat                              | strings |
| PASS   |    0.00 | TestRepeatCatchesOverflow               | strings |
| PASS   |    0.00 | TestRunes                               | strings |
| PASS   |    0.00 | TestReadByte                            | strings |
| PASS   |    0.00 | TestReadRune                            | strings |
| PASS   |    0.00 | TestUnreadRuneError                     | strings |
| PASS   |    0.00 | TestReplace                             | strings |
| PASS   |    0.00 | TestTitle                               | strings |
| PASS   |    0.00 | TestContains                            | strings |
| PASS   |    0.00 | TestContainsAny                         | strings |
| PASS   |    0.00 | TestContainsRune                        | strings |
| PASS   |    0.00 | TestEqualFold                           | strings |
| PASS   |    0.00 | TestCount                               | strings |
| PASS   |    0.00 | ExampleFields                           | strings |
| PASS   |    0.00 | ExampleFieldsFunc                       | strings |
| PASS   |    0.00 | ExampleCompare                          | strings |
| PASS   |    0.00 | ExampleContains                         | strings |
| PASS   |    0.00 | ExampleContainsAny                      | strings |
| PASS   |    0.00 | ExampleContainsRune                     | strings |
| PASS   |    0.00 | ExampleCount                            | strings |
| PASS   |    0.00 | ExampleEqualFold                        | strings |
| PASS   |    0.00 | ExampleHasPrefix                        | strings |
| PASS   |    0.00 | ExampleHasSuffix                        | strings |
| PASS   |    0.00 | ExampleIndex                            | strings |
| PASS   |    0.00 | ExampleIndexFunc                        | strings |
| PASS   |    0.00 | ExampleIndexAny                         | strings |
| PASS   |    0.00 | ExampleIndexByte                        | strings |
| PASS   |    0.00 | ExampleIndexRune                        | strings |
| PASS   |    0.00 | ExampleLastIndex                        | strings |
| PASS   |    0.00 | ExampleLastIndexAny                     | strings |
| PASS   |    0.00 | ExampleLastIndexByte                    | strings |
| PASS   |    0.00 | ExampleLastIndexFunc                    | strings |
| PASS   |    0.00 | ExampleJoin                             | strings |
| PASS   |    0.00 | ExampleRepeat                           | strings |
| PASS   |    0.00 | ExampleReplace                          | strings |
| PASS   |    0.00 | ExampleReplaceAll                       | strings |
| PASS   |    0.00 | ExampleSplit                            | strings |
| PASS   |    0.00 | ExampleSplitN                           | strings |
| PASS   |    0.00 | ExampleSplitAfter                       | strings |
| PASS   |    0.00 | ExampleSplitAfterN                      | strings |
| PASS   |    0.00 | ExampleTitle                            | strings |
| PASS   |    0.00 | ExampleToTitle                          | strings |
| PASS   |    0.00 | ExampleToTitleSpecial                   | strings |
| PASS   |    0.00 | ExampleMap                              | strings |
| PASS   |    0.00 | ExampleNewReplacer                      | strings |
| PASS   |    0.00 | ExampleToUpper                          | strings |
| PASS   |    0.00 | ExampleToUpperSpecial                   | strings |
| PASS   |    0.00 | ExampleToLower                          | strings |
| PASS   |    0.00 | ExampleToLowerSpecial                   | strings |
| PASS   |    0.00 | ExampleTrim                             | strings |
| PASS   |    0.00 | ExampleTrimSpace                        | strings |
| PASS   |    0.00 | ExampleTrimPrefix                       | strings |
| PASS   |    0.00 | ExampleTrimSuffix                       | strings |
| PASS   |    0.00 | ExampleTrimFunc                         | strings |
| PASS   |    0.00 | ExampleTrimLeft                         | strings |
| PASS   |    0.00 | ExampleTrimLeftFunc                     | strings |
| PASS   |    0.00 | ExampleTrimRight                        | strings |
| PASS   |    0.00 | ExampleTrimRightFunc                    | strings |
| PASS   |    0.00 | ExampleBuilder                          | strings |
+--------+---------+-----------------------------------------+---------+  
</pre>
</details>

**Comment by mfridman** [comment]
@egonelbre I like this a lot actually, thanks for the improvement suggestion.

**Comment by mfridman** [comment]
This should be working as of https://github.com/mfridman/tparse/releases/tag/v0.7.3

<img width="1038" alt="screen shot 2019-02-18 at 7 50 15 pm" src="https://user-images.githubusercontent.com/6278244/52982961-d610cb00-33b6-11e9-8f69-733d4d02df92.png">

**Comment by egonelbre** [comment]
Looks nice, but slightly different from what I had in mind. The differences are that:

1. I would still like the full output.
2. The sorting of slow ones is from all packages.

So the slow section based on my local results would look like:

<img width="402" alt="screen shot 2019-02-19 at 06 46 10" src="https://user-images.githubusercontent.com/192964/52990686-15203a00-3412-11e9-89ce-627d75575adf.png">

The main reason for combining packages is that when you have ~100 of them then finding or noticing slow tests is still difficult.
