### ISSUE TITLE
Support for -coverpkg=./...

### ISSUE THREAD

**Issue by screwyprof** [mfridman/tparse#55]
I've noticed that when I add `-coverpkg=./...` flag the coverage is not shown.

Bellow is an example of the command I use to run the tests:
```
go test -json -tags=integration -v -race -count=1 -timeout=120s -covermode atomic -cover -coverpkg=./...  ./... | tparse -all
```

If I run it without `-coverpkg=./...` the coverage is shown for unit tests, but not shown for integration tests. 

Is it possible to show coverage for integration tests?

**Comment by mfridman** [comment]
I believe this should be possible. The go command dumps that value so we should be able to detect it.

Jotting this down so I don't forget. I assume in the example below you're looking for ` 35.5%` to be output in the COVER table? fwiw this is where the `-cover` value is output, but iirc only one of these is returned, so using this field seems sane.

```
$ go test  -tags=integration -v -race -count=1 -timeout=120s -covermode atomic -cover  -coverpkg=./... ./... 
...
PASS
coverage: 35.5% of statements in ./...
ok  	github.com/mfridman/tparse/parse	0.325s	coverage: 35.5% of statements in ./...

$ go test  -tags=integration -v -race -count=1 -timeout=120s -covermode atomic -cover  ./...
ok  	github.com/mfridman/tparse/parse	0.289s	coverage: 93.3% of statements
...
PASS
coverage: 93.3% of statements
ok  	github.com/mfridman/tparse/parse	0.289s	coverage: 93.3% of statements
```
