### ISSUE TITLE
tparse `v0.11.0` lost color?

### ISSUE THREAD

**Issue by embano1** [mfridman/tparse#76]
Please see the following output for different versions when running `tparse` against [this repo](https://github.com/embano1/vsphere). `v0.11.0` seems to have lost color? Is there a way to debug this?

## `v0.11.0`

<img width="713" alt="image" src="https://user-images.githubusercontent.com/15986659/177810438-2e4996fa-06e2-4d6d-a120-1b278bddf630.png">

## `v0.10.3`

<img width="713" alt="image" src="https://user-images.githubusercontent.com/15986659/177810617-9c61c7e6-7522-402f-b828-709aafeca484.png">

**Comment by mfridman** [comment]
In a previous release `tparse` was always setting:

```
lipgloss.SetColorProfile(termenv.TrueColor)
```

But then I changed it to only set that when `CI=true`, which set in most envionments.

https://github.com/mfridman/tparse/blob/e2da1ad98541a56759a35afa743d5e0432041175/internal/app/console_writer.go#L65-L76

I suppose we could always set this, but it feels a bit awkward.

**Comment by embano1** [comment]
Reason I was asking is that I was used to running my tests locally and piping to `tparse`. So just wondering why that stopped being coloured :)

**Comment by mfridman** [comment]
I'm a bit stumped why colors don't display in your local terminal. I'll remove the conditional "CI" check, and add this line:

```
lipgloss.SetColorProfile(termenv.TrueColor)
```

But tbh I don't understand why this is needed. Maybe @caarlos0 knows?

---

I have native Terminal and VS Code, and both render colors.

<img width="922" alt="CleanShot 2022-07-10 at 08 41 16@2x" src="https://user-images.githubusercontent.com/6278244/178145336-7261d006-ac4e-474e-af73-427c6e015074.png">

<img width="702" alt="CleanShot 2022-07-10 at 08 42 28@2x" src="https://user-images.githubusercontent.com/6278244/178145352-27b46a21-278c-42a2-a313-ad171dbfb971.png">

**Comment by mfridman** [comment]
Based on a cursory scan of [muesli/termenv](https://github.com/muesli/termenv), there is a check for "CI" env flag that disables colors in GitHub actions:

https://github.com/muesli/termenv/blob/55e6225a50df5a672ccb5a99b43bf2b0a70aba3e/termenv.go#L34-L40

This is what I was observing with GitHub Actions CI, noted here https://github.com/charmbracelet/lipgloss/issues/74#issuecomment-1133744453

So, adding the explicit `lipgloss.SetColorProfile(termenv.TrueColor)` was necessary for CI environments.

For whatever reason, `termenv` is not properly? detecting your env and setting the colors.

https://github.com/muesli/termenv/blob/55e6225a50df5a672ccb5a99b43bf2b0a70aba3e/termenv.go#L42-L50

**Comment by mfridman** [comment]
Pushed a fix in [`v0.11.1`](https://github.com/mfridman/tparse/releases/tag/v0.11.1). This essentially reverts the explicit CI check, so colors should show up for you as before.

**Comment by embano1** [comment]
Awesome, works :)

**Comment by muesli** [comment]
Indeed, I introduced the `CI` check as a workaround for some CI systems that pretend to be a proper terminal, but then never respond to any OSC queries, causing them to timeout. GitHub workflows always behaved fine in that regard, but CircleCI and others didn't.

**Comment by embano1** [comment]
> maybe @embano1 has a `CI` env set locally somehow? `env | grep CI` shows anything?

was my first guess, nothing set. Using tmux with oh my zsh on latest osx.
